# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'
source 'https://cdn.cocoapods.org'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'composeApp', :path => '../composeApp'
#   pod 'YCProductSDK-Swift' , '0.4.2'
#   pod 'AWSChimeSDKIdentity', '~> 2.40'

end